### PR TITLE
test-inbinit.c: migrate to gdbus

### PR DESCRIPTION
**Pull request by yetist**
How to test:
1. Run the follow command in a terminal:
```
$ dbus-monitor --session "interface=org.gnome.SessionManager"
```
2. Open new terminal, build and run `./test-inhibit`
3. Switch to the first terminal, then you can see the output like this:
```
method call time=1556602638.013093 sender=:1.305 -> destination=:1.5 serial=13 path=/org/gnome/SessionManager; interface=org.gnome.SessionManager; member=Inhibit
   string "caja-cd-burner"
   uint32 71303175
   string "A CD burn is in progress."
   uint32 7
signal time=1556602638.013518 sender=:1.5 -> destination=(null destination) serial=1031 path=/org/gnome/SessionManager; interface=org.gnome.SessionManager; member=Inhib
itorAdded
   object path "/org/gnome/SessionManager/Inhibitor74"
method call time=1556602638.014051 sender=:1.23 -> destination=:1.5 serial=329 path=/org/gnome/SessionManager; interface=org.gnome.SessionManager; member=IsInhibited
   uint32 8
method call time=1556602638.014550 sender=:1.23 -> destination=:1.5 serial=330 path=/org/gnome/SessionManager; interface=org.gnome.SessionManager; member=IsInhibited
   uint32 4
method call time=1556602661.376716 sender=:1.305 -> destination=:1.5 serial=14 path=/org/gnome/SessionManager; interface=org.gnome.SessionManager; member=Uninhibit
   uint32 987600594
signal time=1556602661.377701 sender=:1.5 -> destination=(null destination) serial=1035 path=/org/gnome/SessionManager; interface=org.gnome.SessionManager; member=InhibitorRemoved
   object path "/org/gnome/SessionManager/Inhibitor74"
```

During the `test-inhibit` run, you can run `d-feet` to see more information about `/org/gnome/SessionManager/Inhibitor74`.

Default timeout is 30 seconds at 169 line of `test-inhibit.c`.

### CODE REVIEW

**Comment by raveit65** [comment]
When test-inhibit will be used, btw. how can this be tested?
You should reword commit message :) 
test-inbinit.c --> test-inhibit.c

**Comment by yetist** [comment]
Rebase on master and changed the commit message.

**Comment by yetist** [comment]
> (test-inhibit:16561): dbind-WARNING **: 23:42:29.944: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-NcGgRnm6Mg: Connection refused 

These output is not related to this PR, if you replace `test-inhinit` with other gtk3 app, maybe get the same message in the same run environment.

> and this backtrace if run in gdb:
> #22 0x000055555555519c in main (argc=<optimized out>, argv=<optimized out>)
>     at test-inhibit.c:161
>         res = <optimized out>
>         dialog = <optimized out>
> (gdb)

The 161 line of test-inhibit.c is `gtk_init (&argc, &argv)`, so you should run test-inhibit in X environment.

**Comment by lukefromdc** [comment]
This is in an X environemnt, MATE does not yet support wayland

**Comment by lukefromdc** [comment]
Did NOT work for me, I got 
(test-inhibit:5665): dbind-WARNING **: 21:58:40.305: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-FnCfxBcj3r: Connection refused
Trace/breakpoint trap

and I get those kind of warnings a LOT, some kind of ATK problem maybe? Thus my test of this should probably be considered invalid and no reason not to merge this. I don't have time to track that down right now.

**Comment by lukefromdc** [comment]
I got this in terminal 1 in repeated attempts:
```

Monitoring signals from all objects owned by org.gnome.SessionManager
The name org.gnome.SessionManager is owned by :1.7
/org/gnome/SessionManager: org.gnome.SessionManager.ClientAdded (objectpath '/org/gnome/SessionManager/Client11',)
/org/gnome/SessionManager: org.gnome.SessionManager.ClientRemoved (objectpath '/org/gnome/SessionManager/Client11',)
/org/gnome/SessionManager: org.gnome.SessionManager.ClientAdded (objectpath '/org/gnome/SessionManager/Client12',)
/org/gnome/SessionManager: org.gnome.SessionManager.ClientRemoved (objectpath '/org/gnome/SessionManager/Client12',)

In  terminal 2 I got 
```

luke@ubuntu:~$ '/home/luke/Desktop/Development/MATE_Development_Work/mate-session-manager_1.23.0+git20190424/mate-session/test-inhibit' 

(test-inhibit:4743): dbind-WARNING **: 21:57:10.334: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-FnCfxBcj3r: Connection refused
Trace/breakpoint trap
luke@ubuntu:~$ cd '/home/luke/Desktop/Development/MATE_Development_Work/mate-session-manager_1.23.0+git20190424/mate-session' 
luke@ubuntu:~/Desktop/Development/MATE_Development_Work/mate-session-manager_1.23.0+git20190424/mate-session$ ./test-inhibit

(test-inhibit:5086): dbind-WARNING **: 21:57:45.119: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-FnCfxBcj3r: Connection refused
Trace/breakpoint trap
luke@ubuntu:~/Desktop/Development/MATE_Development_Work/mate-session-manager_1.23.0+git20190424/mate-session$ ./test-inhibit


```
In terminal 3 I got 

```
luke@ubuntu:~$  gdbus introspect --session --dest "org.gnome.SessionManager" --object-path "/org/gnome/SessionManager/Inhibitor2"
node /org/gnome/SessionManager/Inhibitor2 {
};
luke@ubuntu:~$ node /org/gnome/SessionManager/Inhibitor2


```
```

**Comment by yetist** [comment]
@lukefromdc 

Can the original `./test-inhibit` (before this PR) work in your environment?

**Comment by lukefromdc** [comment]
The original version worked: if I run it from terminal, keep the gui dialog showing, then try to switch user I get the error dialog saying a CD is being burned and has not finished

**Comment by lukefromdc** [comment]
I still cannot get this to work, even after running 
` gdbus monitor --session --dest org.gnome.SessionManager`

```

./test-inhibit

(test-inhibit:5581): dbind-WARNING **: 21:06:18.698: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-BOZz2sDWuC: Connection refused
Trace/breakpoint trap
luke@ubuntu:~/Desktop/Development/MATE_Development_Work/mate-session-manager_1.23.0+gdbus20190506/mate-session$ 

```

I think I've got some kind of accessability bus error here, which I do not have time to track down right now. I very often see similar warnings on other programs but with no other effect. Thus, my failed test should be considered invalid.

**Comment by raveit65** [comment]
@lukefromdc 
I noticed such warnings with nearly every application in fedora rawhide or 30 the last 3 months.
I think newer atk itself is still buggy. Or something is change in atk but nobody did inform us.
But for some reasons those warnings arent't crashes here.
eg.
```
[rave@mother ~]$ mate-system-monitor 

(mate-system-monitor:2732): dbind-WARNING **: 15:24:27.206: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
And i know from other fedora maintainer that those warnings still exists in cinnamon.

**Comment by lukefromdc** [comment]
Normally when I am testing packages, I have root Nemo windows open (for editing checkinstall .debs), so maybe that is causing the problem? I cannot test this code without trashing my session every time(running from master at the moment), which is a nuisance.

**Comment by lukefromdc** [comment]
I'm pretty sure when I've tested this on a new session Nemo has not been open on that session. Uusually I have restarted all of X but at least one test was logging out rather than restarting X.

**Comment by lukefromdc** [comment]
I don't have time right now to try and diagnose that as I have been hammered with
other things. Since its not specific to this feel free to merge.

**Comment by lukefromdc** [comment]
I have not been able to find or fix this issue on my system in over a year. It should not block this or any other PR.

**Pull request merged**
