### PR TITLE
Guard against missing systemd

### LINKED ISSUE #190: mate-session-manager-1.22.0 FTBFS

### PR DESCRIPTION
**Pull request by vkareh**
Build fails without systemd support. I've added some guards against that scenario.

Fixes #190

### CODE REVIEW

**Comment by bunder2015** [comment]
works for me on gentoo building 1.22.0

**Comment by vkareh** [comment]
@lukefromdc - no need to install, but could you confirm whether it builds for you if you configure with the `--without-systemd` flag? It builds for me on Fedora, tomorrow I'll test building it on Ubuntu

**Comment by dhgutteridge** [comment]
FWIW, I've applied a similar patch to fix builds on non-Linux systems (NetBSD, SmartOS, et al.) via pkgsrc.org and am running mate-session-manager 1.22 under NetBSD without issue.

**Comment by lukefromdc** [comment]
Build with  --without-systemd went fine too, no problem

**Comment by vkareh** [comment]
Okay, I've gotten a lot of positive confirms from folks on IRC and GitHub that this patch works. It also builds well for me on both Ubuntu and Fedora, with or without the systemd flag.

I'm merging.

**Pull request merged**
