### PR TITLE
Make QT5 apps follow the GTK style

### PR DESCRIPTION
**Pull request by clefebvre**
You can use dropbox systray to test:

- Without this, the menu uses the QT style (white with blue highlight)
- With this, the menu looks like according to your GTK style

### CODE REVIEW

**Comment by raveit65** [comment]
real nice, works well with dropbox applet menu.
+1

**Comment by flexiondotorg** [comment]
This variable doesn't need to be set in the session manager. I've been setting this via Xsession.d. It is also worth noting some Qt apps will segfault with this variable set.

**Comment by monsta** [comment]
Yes, ```/etc/X11/Xsession.d/``` might be a better place for it. Current solution doesn't affect Qt5 apps running as root...

@flexiondotorg: maybe this better be done at distro level rather than in all GTK+ desktop environments out there...

**Comment by flexiondotorg** [comment]
@monsta Yes, I would prefer this to be directly user configurable in case of regression.

**Comment by clefebvre** [comment]
Ok, I'll fix it in Mint specifically then.

**Comment by lukefromdc** [comment]
How do you go about doing this in /etc/X11/Xsession.d? I NEED this functionality as otherwise I have to manually change every panel launcher and menu entry for QT5 apps to force the theme.

**Comment by flexiondotorg** [comment]
@lukefromdc You'll find how I do it in Ubuntu MATE here - https://code.launchpad.net/~ubuntu-mate-dev/ubuntu-mate/ubuntu-mate-settings

**Comment by lukefromdc** [comment]
Thanks! That worked for me, and I don't have any of the apps that segfault over it.

**Pull request closed without merging**
