### PR TITLE
mate-session-save: try org.mate.SessionManager if org.gnome fails

### PR DESCRIPTION
**Pull request by monsta**
fixes https://github.com/mate-desktop/mate-session-manager/issues/103

### CODE REVIEW

**Comment by clefebvre** [comment]
+1

**Comment by flexiondotorg** [comment]
+1

**Comment by raveit65** [comment]
if it works for you +1

**Comment by phattl** [comment]
I don't understand, how do I use org.mate.SessionManager?

**Comment by clefebvre** [comment]
It's not used anymore, this just fixed a particular case during an upgrade.

**Pull request merged**
