### PR TITLE
autostart: fix disabling services in dialog

### PR DESCRIPTION
**Pull request by raveit65**
- fixes https://github.com/mate-desktop/mate-session-manager/issues/156

Steps to reproduce the issue and testing the fix see https://github.com/mate-desktop/mate-session-manager/issues/156#issuecomment-808731386
and
https://github.com/mate-desktop/mate-session-manager/issues/156#issuecomment-808893461

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
I just tested this, and had no trouble turning either my custom startup jobs or mate-session-manager on and off

**Comment by lukefromdc** [comment]
This one's important, we need to get this finished and merged before the unstable release

**Comment by raveit65** [comment]
Yes, this also needs to be go in 1.24 branch.

**Comment by rbuj** [comment]
IMHO, I don't think it's a good idea to remove the check to avoid adding the app if it already exists from `append_app` method. I think we need to review the `find_by_app` method where it checks that the apps are not the same, as it currently compares the pointers of the objects instead of their content.

**Comment by raveit65** [comment]
I only took that code from https://github.com/mate-desktop/mate-session-manager/issues/156#issuecomment-809557273
But feel free to find a better solution to fix that issue.
Btw. i used that patch already in latest fedora package, in result the issue isn't reproducible with standard installation.

**Review by rbuj — CHANGES_REQUESTED** [review]
It adds a regression as it shows all applications after launching `mate-session-properties` because it removes `update_tree_view` call after calling `populate_model`.

**Comment by raveit65** [comment]
@rbuj 
again, I only took that code from #156 (comment)
But feel free to find a better solution to fix that issue when you know it better.

**Pull request closed without merging**
